Check SM version before calling flash attention with BFloat16
The flash attention code path requires sm80 or newer to run on
BFloat16, so any OpInfo tests running with BFloat16 would fail with
the error:
```
RuntimeError: Expected q_dtype == at::kHalf || (is_sm8x && q_dtype == at::kBFloat16) to be true, but got false.
```

ghstack-source-id: 95e4d520b89b76329d3630cdc4d63a2cb669acc9
Pull Request resolved: https://github.com/pytorch/pytorch/pull/86600